# Generated by Django 5.0.1 on 2024-01-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('time_recorded', models.DateField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_recorded'],
                'indexes': [models.Index(fields=['-time_recorded'], name='tracker_wei_time_re_8de48a_idx')],
            },
        ),
    ]
