# Generated by Django 5.0.1 on 2024-01-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightrecord',
            options={'ordering': ['-date_recorded']},
        ),
        migrations.RemoveIndex(
            model_name='weightrecord',
            name='tracker_wei_time_re_8de48a_idx',
        ),
        migrations.RenameField(
            model_name='weightrecord',
            old_name='time_recorded',
            new_name='date_recorded',
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['-date_recorded'], name='tracker_wei_date_re_0ce272_idx'),
        ),
    ]
