# Generated by Django 4.2.9 on 2024-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_weightrecord_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightrecord',
            name='body_fat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
